name: Update starred repositories

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://gh-starred-repos-feed.cheeaun.workers.dev/nishith-p-shetty.rss'
          file: 'README.md'
          start_flag: '<!-- starred repos start -->'
          end_flag: '<!-- starred repos end -->'
          timezone: 'Asia/Kolkata'
          format: '- [${title}](${url})'
          max_entry: 15
      # - uses: sarisia/actions-commit@master
      - uses: nishith-p-shetty/actions-commit@master
